# Generated by Django 3.2.13 on 2023-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('how_often', models.CharField(choices=[('Never', 'N'), ('Sometimes', 'S'), ('Always', 'A')], max_length=50)),
                ('review', models.CharField(choices=[('Rotten', 'R'), ('Fresh', 'F'), ('Very fresh', 'V')], max_length=50)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=70)),
                ('genre', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
